### ISSUE TITLE
Importing CreateEventDispatcher always throws (Related Issues)

### ISSUE THREAD

**Issue by netaisllc** [plentico/plenti#123]
By simply including the typical Svelte import statement for `createEventDispatcher`, a Plenti site will throw an error to the browser console like this:

`Uncaught SyntaxError: The requested module '/spa/web_modules/svelte/transition/index.js' does not provide an export named 'createEventDispatcher'`

Plenti version: 0.3.13
Svelte version: 3.29.4

I'm guessing this is related to issues #38 and #92, wherein the latter issue provides a simple workaround. Maybe this issue title will be more discoverable.

**Comment by jimafisk** [comment]
You're exactly right, does it work if you use `import { createEventDispatcher } from "svelte/internal";`?

I actually have a commit already merged that should fix this, just need to do another release... maybe tonight? Thanks for flagging @netaisllc!

**Comment by jimafisk** [comment]
This should be all set now in [v0.3.15](https://github.com/plentico/plenti/releases/tag/v0.3.15). I just tested locally using [this example](https://svelte.dev/tutorial/component-events) and it seems to work:

<details>
<summary>See screenshot</summary>

![event_dispatcher](https://user-images.githubusercontent.com/5913244/105446320-e1726e00-5c3f-11eb-9f0d-0e1d1e7708c9.png)


</details>

Just let me know if it's still not working for you for some reason, thanks!

**Comment by netaisllc** [comment]
Fixed in `0.3.15` 🥇

**Comment by jimafisk** [comment]
Thanks for testing @netaisllc!
