### ISSUE TITLE
What about ssr in Plenti?

### ISSUE THREAD

**Issue by Valexr** [plentico/plenti#128]
How Plenti friendship with SEO?

**Comment by jimafisk** [comment]
It should be pretty good! Every route automatically gets an HTML fallback so initial page load should be fast and easy for search engines to crawl. We do SSR behind the scenes during the build process that we automatically [render out to HTML](https://svelte.dev/docs#Server-side_component_API), but Plenti is a [JAMstack](https://jamstack.org/what-is-jamstack/) framework so if you're hoping to host a fullstack app on a server and run your own SSR, there are probably better options, like [Sapper](https://sapper.svelte.dev/) (soon to be sveltekit). There are a lot of aspects to SEO, so you'll still need to take care of your metadata, use semantic markup, optimize for mobile, etc but you should be able to do all that in Plenti. Hope that helps and if you need further clarification on anything just let me know!
