### ISSUE TITLE
What about LiveReload?

### ISSUE THREAD

**Issue by Valexr** [plentico/plenti#133]
```plenty serve``` on Save don't reload page in browser 🤷🏻‍♂️

**Comment by jimafisk** [comment]
This a great idea @Valexr, and it's something a few people have been asking for. I realize Hot Module Reloading (HMR) and Live Reload aren't necessarily the same thing, but there's a conversation touching on both these topics happening over at https://github.com/plentico/plenti/issues/99. I'm going to close this for now to consolidate conversations, thanks!
