### ISSUE TITLE
homebrew - Error: Cannot tap plentico/plenti: invalid syntax in tap!

### ISSUE THREAD

**Issue by Valexr** [plentico/plenti#141]
After last update - Error: Cannot tap plentico/plenti: invalid syntax in tap!

![Screenshot 2021-02-23 at 22 36 31](https://user-images.githubusercontent.com/5656366/108898043-c5d7fa00-7627-11eb-871d-2f3556d35f48.jpg)

**Comment by jimafisk** [comment]
Oh jeeze! It looks like there's still a valid url: https://github.com/plentico/homebrew-plenti/blob/cf98f5b92cbbff8d5347c128edd582be9af673a4/plenti.rb#L12

Not sure if it's related to: https://github.com/Homebrew/legacy-homebrew/issues/22707

I'll look into it, thanks for flagging @Valexr!

**Comment by stephanieluz** [comment]
I reset my system:
- `brew uninstall plenti`
- `brew untap plentico/homebrew-plenti`

Then tried retapping and reinstalling:
- `brew tap plentico/homebrew-plenti`
- `brew install plenti`

That seemed to work:

<img width="1279" alt="Screen Shot 2021-04-01 at 2 34 08 PM" src="https://user-images.githubusercontent.com/17965122/113338878-b703f780-92f7-11eb-9992-26689f5bd19c.png">

Has this been resolved for you as well @Valexr?

**Comment by Valexr** [comment]
> I reset my system:
> 
> * `brew uninstall plenti`
> * `brew untap plentico/homebrew-plenti`
> 
> Then tried retapping and reinstalling:
> 
> * `brew tap plentico/homebrew-plenti`
> * `brew install plenti`
> 
> That seemed to work:
> 
> <img alt="Screen Shot 2021-04-01 at 2 34 08 PM" width="1279" src="https://user-images.githubusercontent.com/17965122/113338878-b703f780-92f7-11eb-9992-26689f5bd19c.png">
> 
> Has this been resolved for you as well @Valexr?

yep! tx @stephanieluz
