### ISSUE TITLE
Define _blueprint.json allowed values

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#15]
The keys for `_blueprint.json` are flexible since they correspond to field values in the content source, which have no restrictions. The values however should be optional (can be left as `""` if desired), but should be pull from a predefined list. Ultimately this will inform the editing behavior of the CMS that will get injected at build time.

**Comment by jimafisk** [comment]
Related to https://github.com/plentico/plenti/issues/24

**Comment by jimafisk** [comment]
The purpose of the `_blueprint.json` has been evolving somewhat in my mind. I'm thinking its best use is probably a simple template for default content. That way if we ever make a command to automatically generate new content pages (e.g. `plenti gen 10 blog`) it could simply copy the blueprint. That would mean the key/value structure of this file would look like any other JSON content file. This could also plug into the git-cms for creating new pages of a certain type. Without some sort of default content, a primarily "in-page" editing experience could be difficult. This change does beg the questions of how the git-cms gets instructions for the field types it needs for a particular content type. I'm playing with the idea in my head that this is mainly discovered from the HTML structure itself (e.g. Text within elements like `<h1>`, `<p>`, `<span>` etc would be content editable, while `<img>` would get a specific widget, `<a>` would get a specific widget). This obviously is more complicated in practice than in theory, so I'll save that discussion for a separate thread.

**Comment by jimafisk** [comment]
This is covered by https://github.com/plentico/plenti/issues/7

**Comment by jamestagal** [comment]
Hi @jimafisk 
I just wanted to ask how should I define the ```_blueprint.json``` file in my ```Content/Pages``` folder to allow me to add content on the page? At present I just have curly brackets as below.

![Screen Shot 2022-08-09 at 9 58 06 pm](https://user-images.githubusercontent.com/6309595/183641823-1feb355c-88dc-4cfd-a7d2-38a4247a5301.png)

Cheers,
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

So currently `_blueprint.json` is simply being used as default values. So what you could do to get started is just copy the JSON from another page of that "type" and paste it into the blueprint. That CMS _should_ pick up on this and allow you to add new content of that type with the defaults you defined.

I've been thinking a lot about the longer term plan for blueprints. We need a way to override the default field types that the CMS tries to discover. I've talked about adding `_schema.json` files loosely based on https://json-schema.org/ to accomplish this (https://github.com/plentico/plenti/issues/204). I'm starting to think that maybe we should allow blueprints to determine both default values and field schema. If we go that route, I'd like you to be able to still be able to simply define default values like discussed above if you don't want to get into the schema side of things, and allow you to mix and match (define simple defaults for some keys and defined schema for others) if you'd like.

**Comment by jamestagal** [comment]
Hi @jimafisk 
Thanks. I just copied over the content from the ```admin.json``` file, see below, but that still didn't work. Maybe I've got the ```_blueprint.json``` file in the wrong folder? https://gitlab.com/MyPlentiSite/my-plenti-site/-/tree/master/content

```json
{
	"title": "This is a new page",
	"description": [
		"The Git-CMS is still under active development and is experimental.",
		"Make sure to add your GitLab backend CMS info to plenti.json to test it out.",
		"If you want things to move faster, please consider showing <a href='https://github.com/sponsors/plentico' target='blank' rel='noopener noreferrer'>your support</a>. Thanks!"
	],
	"cms": true,
	"source": {
		"layout": true,
		"content": true
	}
}
```

**Comment by jimafisk** [comment]
Yeah it looks like the `_blueprint.json` file was just in the wrong place: `content/_blueprint.json` instead of `content/pages/_blueprint.json`. I just pushed a fix for this to your repo. Essentially you need a blueprint for each content type if you want to be able to create new pages of that type via the editor. So if you want to create blog pages, you'd need a `content/blog/_blueprints.json` too (I pushed a change for this as well).
