### ISSUE TITLE
Please use releases so I can follow the project

### ISSUE THREAD

**Issue by frederikhors** [plentico/plenti#16]
Please use releases so I can watch with "Releases only".

Thanks for your amazing work!

**Comment by jimafisk** [comment]
@frederikhors thanks for checking out the project! It should be using [Goreleaser](https://goreleaser.com/) to automatically create the binaries that you can download here: https://github.com/plentico/plenti/releases

I still need to extend this for a few additional operating systems (like Windows and FreeBSD), but the Linux and Mac (Darwin) versions should be available. Is there something else I could be doing to make this work for you? Thanks!
