### ISSUE TITLE
permission denied at plenti new, ubuntu

### ISSUE THREAD

**Issue by j2l** [plentico/plenti#163]
Hello, 
Great project!
`sudo snap install plenti ` went well but `plenti new site plentitest` throws `permission denied` on each line while ending on:
```
2021/07/20 15:31:37 errs.go:55: Unable to create directory plentitest: mkdir plentitest: permission deniedmkdir plentitest: permission deniedpermission denied
2021/07/20 15:31:37 errs.go:55: Unable to create path(s) .: mkdir plentitest: permission denied
2021/07/20 15:31:37 errs.go:55: Unable to write file: open plentitest/.gitignore: no such file or directoryopen plentitest/.gitignore: no such file or directoryno such file or directory
2021/07/20 15:31:37 errs.go:55: Unable to create path(s) assets: mkdir plentitest: permission denied
2021/07/20 15:31:37 errs.go:55: Unable to write file: open plentitest/assets/logo.svg: no such file or directoryopen plentitest/assets/logo.svg: no such file or directoryno such file or directory
2021/07/20 15:31:37 errs.go:55: Unable to create path(s) content: mkdir plentitest: permission denied
...
Success: Created "plentitest" site.

We suggest that you begin by typing:

  cd plentitest
  plenti serve
```
mkdir is working at this location though.
Maybe Go doesn't use the userid 1000?

Ubuntu 20.04

**Comment by jimafisk** [comment]
Thanks for reporting this @j2l! I use Ubuntu 20.04 as well so I'll do some testing with a fresh install to see if I can recreate this bug.

**Comment by jimafisk** [comment]
I just ran a test with a fresh install and it seemed to work on my end...

<details>
<summary>See screenshot</summary>

![plenti](https://user-images.githubusercontent.com/5913244/126352066-38fd4b89-0d08-41d6-8a98-f6868cec0137.png)

</details>

Can you let me know which version you're using (`plenti --version`)? Do you need `sudo` to create the folder at that location on your filesystem? Thanks!

**Comment by j2l** [comment]
Sure: v0.4.25
No sudo needed, it's my github folder to test projects.
Here's mkdir before plenti:
![image](https://user-images.githubusercontent.com/65325/126353886-df928aa5-a893-4448-9f7e-9bfd7e2e21b7.png)

**Comment by j2l** [comment]
I think I found the bug, it's not plenti's fault, it's just the default behavior in the snap store, at least on mine:
![image](https://user-images.githubusercontent.com/65325/126354345-e8dc38f2-8f05-4950-b4ce-883e00a2eadc.png)

So `snap install` applies the snap store default permissions.
This "removable" drive is my 1TB SSD :smile:

**Comment by j2l** [comment]
Maybe, adding a "use the snap store to allow permissions if you plan to use it on a secondary drive"

**Comment by jimafisk** [comment]
This is super helpful to know, thanks for debugging @j2l! I'm sure other folks will run into this, I'll update the documentation.
