### ISSUE TITLE
:unneeded is deprecated

### ISSUE THREAD

**Issue by greg-raven** [plentico/plenti#167]
Just got this message:

Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the plentico/plenti tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/plentico/homebrew-plenti/plenti.rb:9

**Comment by jimafisk** [comment]
Thanks for reporting this @greg-raven! Looks like our formula is using [bottle :unneeded](https://github.com/plentico/homebrew-plenti/blob/master/plenti.rb#L9) but it was [deprecated in June 2021](https://stackoverflow.com/questions/45132704/what-does-bottle-unneeded-do/45163490#45163490). We use Goreleaser to build our formula and it looks like this was [reported](https://github.com/goreleaser/goreleaser/issues/2595) and [fixed](https://github.com/goreleaser/goreleaser/pull/2591) 27 days ago. My hope is this will resolve automatically on the next Plenti release, I'll leave this open to confirm.

**Comment by jimafisk** [comment]
I released [v0.4.28](https://github.com/plentico/plenti/releases/tag/v0.4.28) last night, and it looks like `bottle :unneeded` was removed from [our formula](https://github.com/plentico/homebrew-plenti/blob/master/plenti.rb), so I'm hoping this is resolved. Anyone with a Mac want to try upgrading to the newest version to test this out? Thanks!

**Comment by stephanieluz** [comment]
0.4.30 looks ok on my mac
