### ISSUE TITLE
Poor first time user experience because of directory name change layout to layouts

### ISSUE THREAD

**Issue by SumitBando** [plentico/plenti#168]
$ plenti new site my-new-site
$ cd my-new-site/
$ plenti serve

Building...  errs.go:57: Could not get layout: can't stat layouts: lstat layouts: no such file or directory /home/runner/work/plenti/plenti/cmd/build/client.go on line 163

**Comment by SumitBando** [comment]
Putting plenti in PATH seems to solve above issue, and other path issues

**Comment by jimafisk** [comment]
Thanks for documenting and posting the solution @SumitBando, just let me know if you hit other roadblocks!
