### ISSUE TITLE
Can't download theme

### ISSUE THREAD

**Issue by stephanieluz** [plentico/plenti#182]
When I run `plenti new site my-site --theme=git@github.com:plenti-themes/bigspring` it throws:

```
022/03/18 17:20:07 errs.go:57: Can't clone theme repository: unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable
unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable (File: /home/runner/work/plenti/plenti/cmd/theme_add.go, Line: 75)
2022/03/18 17:20:07 errs.go:57: Can't get HEAD: reference not found
reference not found (File: /home/runner/work/plenti/plenti/cmd/theme_add.go, Line: 84)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x985965]

goroutine 1 [running]:
github.com/go-git/go-git/v5/plumbing.(*Reference).Hash(...)
	/home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/reference.go:183
github.com/plentico/plenti/cmd.getCommitHash(0xc0001a9c80, 0x18, 0x7fff9711615f)
	/home/runner/work/plenti/plenti/cmd/theme_add.go:87 +0x125
github.com/plentico/plenti/cmd.glob..func6(0x2404c00, 0xc00007d6c0, 0x1, 0x2)
	/home/runner/work/plenti/plenti/cmd/site.go:103 +0x4b8
github.com/spf13/cobra.(*Command).execute(0x2404c00, 0xc00007d6a0, 0x2, 0x2, 0x2404c00, 0xc00007d6a0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2404700, 0xc000000180, 0x200000003, 0xc000000180)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/plentico/plenti/cmd.Execute()
	/home/runner/work/plenti/plenti/cmd/root.go:58 +0x31
main.main()
	/home/runner/work/plenti/plenti/main.go:7 +0x25
```

I thought it might be because I didn't have an SSH key uploaded to GitHub, but the problem still persists even after adding it.

Possibly related to https://github.com/src-d/go-git/issues/454

**Comment by sanati** [comment]
I had the same error. 
I tried another way:
1. plenti new site YOUR_SITE_NAME
2. cd YOUR_SITE_NAME
3. plenti theme add https://github.com/plenti-themes/bigspring
4. plenti theme enable bigsprings
5. _Please, copy files/directories from bigsprings to the main dir of YOUR_SITE_NAME (overwriting)_
6. plenti build
7. plenti serve

Thats it!

**Comment by dougwinsby** [comment]
I ran into a similar problem as OP when creating a theme-based site (from linux vm using windows vmware):

```
errs.go:57: Can't clone theme repository: error creating SSH agent:
"Error connecting to SSH_AUTH_SOCK: dial unix /run/user/1000/keyring/ssh: connect: permission denied"
```

I'm running ubuntu 22.04. Github is configured with a ssh key created on that VM, and I tested it with:

```
ssh -T git@github.com
```

I tried the workaround provided by @sanati, but I do not understand no. 5 (copy files/directories). I thought the idea of Plenti templates is so you can run the template with no changes and only override what you need to. Are there certain files I should be copying?

If I copy *all* files/directories from the template, why create a new site at all. Why not simply clone the theme and make it your own site (without a "theme" enabled)?

Any help would be greatly appreciated.

**Comment by jimafisk** [comment]
> I thought the idea of Plenti templates is so you can run the template with no changes and only override what you need to

That's correct @dougwinsby, you should only have to copy the files you want to override. The only required file in your base project should be a `plenti.json` sitewide configuration file (you may need to copy route overrides and other info from the theme's `plenti.json` to your project's `plenti.json`).

Sounds like there might be a bug here. I'll do some testing to see if I can recreate the issue to figure out what's going on.

**Comment by jimafisk** [comment]
If I clear the contents of `~/.ssh/known_hosts` I can still get this working per https://github.com/go-git/go-git/issues/411#issuecomment-977172432:
1. `ssh-keyscan github.com >> ~/.ssh/known_hosts`
2. `plenti new site my-site --theme=git@github.com:plenti-themes/bigspring`

Does something like that work for you @stephanieluz?

**Comment by dougwinsby** [comment]
Thank you @jimafisk for researching this. I haven't used ssh keys with github under linux before (I'm a Windows guy), so this is new to me.

Unfortunately, I was unable to get things working using your suggestions. I keep getting the `permission denied` error: 

<details><summary>connect: permission denied</summary>
2022/05/17 13:17:04 errs.go:57: Can't clone theme repository: error creating SSH agent: "Error connecting to SSH_AUTH_SOCK: dial unix /run/user/1000/keyring/ssh: connect: permission denied"
error creating SSH agent: "Error connecting to SSH_AUTH_SOCK: dial unix /run/user/1000/keyring/ssh: connect: permission denied" (File: /home/runner/work/plenti/plenti/cmd/theme_add.go, Line: 75)
2022/05/17 13:17:04 errs.go:57: Can't get HEAD: reference not found
reference not found (File: /home/runner/work/plenti/plenti/cmd/theme_add.go, Line: 84)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x986565]
</details>

I'm sure it's a problem on my end, but I was able to clone manually and `ssh -T git@github.com` returns successfully. 

Conceptually, I'm struggling with the usefulness of including a theme, though. While I'd like bug fixes from an embedded theme, I wouldn't want an external change to break my site. I think I will just clone a theme as a starting point, and take it from there.

(BTW, I really like this project... thank you for your work on it.)

**Comment by dougwinsby** [comment]
Yes! `--theme=https://github.com/plenti-themes/bigspring.git` worked perfectly. Thank you.

**Comment by stephanieluz** [comment]
Woo that worked!

**Comment by jimafisk** [comment]
Ok great! I'll update the documentation to reflect this, I think it'll be easier for almost everyone.

@dougwinsby to answer your questions:

> Conceptually, I'm struggling with the usefulness of including a theme, though. 

The main advantage is to give the theme creator the ability to push out changes in a centralized way. If 100 people clone a theme and edit it directly, the theme creator would have to work with them individually to accommodate a bug fix, but with themes they can push it once and everyone can get the benefit. You don't need a theme though, you could always watch the original repository yourself and manually pull in any changes you want, or go your own way completely. 

The Plenti API still changes from time to time since we're not at a stable 1.0 release yet, so themes can help you avoid having to pay attention to our changelog. Alternatively if we update the API and it breaks your site, you can always lock the version of Plenti you're using in CI to an older version so your site continues to build successfully (all versions of Plenti are available on our [dockerhub](https://hub.docker.com/repository/docker/plentico/plenti)). 

> While I'd like bug fixes from an embedded theme, I wouldn't want an external change to break my site. 

Themes should only update when you manually pull the changes into your project (i.e. `plenti theme update THEME`). You can always lock a theme at a specific commit if breaking changes are introduced in the future.

> I think I will just clone a theme as a starting point, and take it from there.

This is a perfectly valid approach. Every theme is simply a Plenti website and every Plenti website can be used as a theme. If you don't want upstream changes, simply using another Plenti site as a starting point is the approach with the least overhead.

**Comment by jimafisk** [comment]
Docs are updated: https://github.com/plentico/plenti.co/commit/3b08719a8e77859888ee9e4476872ea3a1d1399b
