### ISSUE TITLE
Use additional npm packages

### ISSUE THREAD

**Issue by richter-martin** [plentico/plenti#203]
How can we use an additional npm package?

I allways get this error (with `plenti serve -L`):
`Could not get all layouts Could not add SSR Component for layouts/content/gallery.svelte: SyntaxError: Invalid or unexpected token /home/runner/work/plenti/plenti/cmd/build/compile.go on line 275`

This happens for every npm packages I'll try to use.
Installing works, but when I'll try to use it, it breaks.

Can someone help me, or maybe add that to the Docs?

**Comment by jimafisk** [comment]
Hi @richter-martin, can you send a link to a repo so I can take a look? Thanks!

**Comment by richter-martin** [comment]
https://github.com/richter-martin/plenti-additional-npm-package

If you uncomment the two blocks: https://github.com/richter-martin/plenti-additional-npm-package/blob/main/layouts/content/index.svelte

You will see the error, and it's not only with that package, I've tried with a lot. I think, I'm doing something wrong.

**Comment by jimafisk** [comment]
Ah yup I see that as well:

```
Can't copy npm module: Module not set in npm config file: node_modules/svelte-image-gallery/package.json
2022/07/08 15:13:11 build.go:160: 
Error in Gopack build step
Can't runPack on public/spa/ejected/router.js 
Can't runPack on public/spa/ejected/main.js 
Can't runPack on public/spa/ejected/layouts.js 
Can't runPack on public/spa/content/index.js 
Can't runPack on  
Could not read file  to convert to esm
open : no such file or directory
```

You're doing it correctly, but it looks like https://github.com/berkinakkaya/svelte-image-gallery doesn't provide ESM support. Plenti doesn't bundle anything, so it can't use the CommonJS `require` statements that NodeJS uses. Instead we read the package.json file of NPM modules and look for ESM support so we can use the browser's native `import` syntax. Lots of modules include this, but not all of them.

It does look like that package is really just an NPM wrapper around a simple svelte component. You could just copy that directly into your project: https://github.com/richter-martin/plenti-additional-npm-package/pull/1

That works locally for me:

<details>
<summary>See screenshot</summary>

![gallery_screenshot](https://user-images.githubusercontent.com/5913244/178057865-2632023b-948b-4d70-a836-51f40d8b09c3.png)

</details>

That alternative would be to ask the module author to add ESM support. Eventually we'll add [esbuild](https://esbuild.github.io/) to Plenti to allow bundling packages like this, just haven't gotten to it yet.

**Comment by richter-martin** [comment]
Thank you

**Comment by Fankhauser-Dominik** [comment]
I wanted to create a Masonry Gallery with Photoswipe Lightbox support:
[Svelte Photoswipe Gallery](https://github.com/Fankhauser-Dominik/svelte-photoswipe-gallery)
How can I convert this into a Plenti conform Package? I'm a little bit lost about how to get that working. I would appreciate it, if someone could help me.
