### ISSUE TITLE
Rename _blueprint.json to _defaults.json

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#218]
You can optionally have two special files in each content type that serve the following functions:
1. Defining the initial content that should be used when creating a new instance of a type
2. Define the type of input field widgets to be used in the CMS editor

Initially we had thought both of the those functions would be accomplished by a single file, that we had previously named `_blueprints.json`. As development progressed we decided that it would be better to have these as separate files:
1. `_defaults.json`
2. `_schema.json`

We initially rolled the default content functionality out to the `_blueprint.json` files that already existed. Now we need to rename this to `_defaults.json` to make its intention clear going forward.

**Comment by jamestagal** [comment]
Hi @jimafisk 
Great work Jim. Thanks for the heads up! I'll rename my files now before upgrading to the latest build! 

Cheers,
Ben

**Comment by jimafisk** [comment]
I was a little worried that "schema" would be hard for people to spell. In trying to figure out the best names for these files, we tried to focus on the simplicity of the word:

<details>

![defaults_1](https://user-images.githubusercontent.com/5913244/193289843-a219e6f1-ef96-4c3c-8157-e1441b12e884.png)
![blueprint_6](https://user-images.githubusercontent.com/5913244/193289845-f8cfb749-e682-4bd9-950f-9d13d2acfc46.png)
![schema_4](https://user-images.githubusercontent.com/5913244/193289846-830d68c1-8e7d-4b68-8a77-ec0357a5ecbf.png)
![model_1](https://user-images.githubusercontent.com/5913244/193289848-9aa35ca3-cf04-4403-a98e-d77ec6c121d9.png)
![widgets_5](https://user-images.githubusercontent.com/5913244/193289851-062cc9ba-beea-4c1c-8576-233c260c8140.png)
![format_1](https://user-images.githubusercontent.com/5913244/193289852-7adc041a-eff7-4ef9-bdc0-90de0af61e92.png)

</details>

It seemed to have the best balance of simplicity and clarity of describing its purpose.

**Comment by jimafisk** [comment]
Should be renamed in [v0.5.15](https://github.com/plentico/plenti/releases/tag/v0.5.15)
