### ISSUE TITLE
Allow content type index files

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#220]
Currently if you have a content type, let's say `pages`, if you try to add a `content/pages/index.json` file, it would create a path like [http:/localhost:3000/pages/index](url). That's because the html fallback actually looks like `pages/index/index.html`. We should provide a way to create a [http:/localhost:3000/pages](url) path (i.e. `pages/index.html`). This happens automatically at the top level `content/index.json` but not within a content type. 

If this existed, in a scenario where you update your `plenti.json` routes to have a content type appear directly off your domain root, you could even omit the top level `content/index.json` file. This would be handy because often times that file is handled the exact same way as a `pages` content type, so it would reduce duplication.

The challenge would be that sometimes someone might actually want a [http:/localhost:3000/index](url) route. If we keep automatically converting `index.json` files like this, then you won't be able to create one. We could change it so true index files have a special naming convention like `_index.json` (converts to `index.html`) and regular `index.json` files get that route (converts to `index/index.html`). That would break existing sites, and I don't love that you need a specially named file to get your homepage working, but it might be the most flexible solution.

**Comment by jamestagal** [comment]
Hi @jimafisk 
How about swapping the proposed file naming and leave the "true" index  as it is ```index.json``` and have the regular ```index.json``` get the underscore ```_index.json```? That change wouldn't break existing sites and then the special names files are only needed if you want or need to architect it in that way!

Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 
Thanks for explaining all this.  I think you make very considered changes and the benefits from this one far out weights any perceived annoyance 😀 Great work Jim.

**Comment by jimafisk** [comment]
I've been implementing the `_index.json` (true index) file functionality. A couple of notes:
- You could continue to use a `content/index.json` as your homepage if you'd like, just add a route override to `plenti.json` for it
- If you use an `content/_index.json` make sure your to update:
  - the corresponding layout to `layouts/content/_index.svelte`
  - any route overrides in `plenti.json` to `"_index": "whatever"`

**Comment by jimafisk** [comment]
This is available in [v0.6.0](https://github.com/plentico/plenti/releases/tag/v0.6.0)
