### ISSUE TITLE
How to inline a file

### ISSUE THREAD

**Issue by notramo** [plentico/plenti#236]
Is it possible to inline a file, with a programmatically generated filename? `import` doesn't work because it only works with literals as filename.

**Comment by jimafisk** [comment]
I'm not sure I exactly understand, can you explain a little more? What kind of file is this, another svelte template or something else? What's generating the filename (Plenti or a 3rd party script?) and where is it getting written to on the filesystem?

**Comment by notramo** [comment]
There are lot of SVG icons imported. For ease of use, I want to create an `icon.svelte` component, with `name` being passed as property. The component would look up the filename, read the file content, then inline it. The difficulty is that the pre-rendering can not use `fetch`, and browser environment doesn't have filesystem I/O.

**Comment by jimafisk** [comment]
Ah yes, I've wanted to do something similar for [Tabler Icons](https://tablericons.com/), but it's harder to [import SVGs in Svelte](https://stackoverflow.com/questions/66069647/best-way-to-import-svg-icons-into-a-svelte-app) than I thought. I ended up doing this:

<details>
<summary>layouts/components/tabler.svelte</summary>

```svelte
<script>
    /**
     * Search Tabler icons at https://tabler-icons.io/
     * 
     * Needed to add IDs to each svg,
     * see script at /layouts/tabler_icons/_addID.sh
     * 
     */
    export let icon;
    export let scale = "1";
    export let color = "white";
    export let background = "transparent";
    export let stroke_width = "2";
    export let width = "25px";
    export let height = "25px";
    export let viewBox = "0 0 24 24";
</script>

<svg {width} {height} {viewBox} style="transform: scale({scale}); color: {color}; background: {background}; stroke-width: {stroke_width};">
    <use href="/spa/tabler_icons/{icon}.svg#{icon}"></use>
</svg>
```

</details>

Then I uploaded all the Tabler SVGs to a `layouts/tabler_icons/` folder.

I also ran 4 bash scripts to prep the icons so I could target them and override their properties:

<details>
<summary>layouts/tabler_icons/_addID.sh</summary>

```bash
#! /bin/bash
for f in *.svg; do 
    base=$(basename "$f" '.svg')
    sed -i "s/<svg/<svg id=\"$base\"/g" "$f"
done
```

</details>

<details>
<summary>layouts/tabler_icons/_removeHeight.sh</summary>

```bash
#! /bin/bash
sed -i "s/\sheight=\"24\"//g" *.svg
```

</details>

<details>
<summary>layouts/tabler_icons/_removeStrokeWidth.sh</summary>

```bash
#! /bin/bash
sed -i "s/\sstroke-width=\"2\"//g" *.svg
```

</details>

<details>
<summary>layouts/tabler_icons/_removeWidth.sh</summary>

```bash
#! /bin/bash
sed -i "s/\swidth=\"24\"//g" *.svg
```

</details>

To run bash scripts just `cd layouts/tabler_icons` and make sure the file is executable `chmod u+x _addID.sh` then run it like `./_addID.sh` (or `./_removeHeight.sh` etc). You can discard the scripts after running them.

<details>
<summary>Actually using the icon in a Svelte template</summary>

```svelte
<script>
    import Tabler from '../components/tabler.svelte';
</script>

<Tabler icon="circle-x" height="50px" color="red" scale="1.25" stroke_width="1.5" />
```
</details>

Does something like that work for you?

**Comment by jimafisk** [comment]
Closing this for now, just let me know if you'd like to discuss more.
