### ISSUE TITLE
Site broken possibly since latest commit 

### ISSUE THREAD

**Issue by jamestagal** [plentico/plenti#245]
hi @jimafisk 
I just noticed [my test Plenti site](https://myplentisite.gitlab.io/my-plenti-site/) that is connected to GitLab is broken. When running the site locally it is working but when I logged in via Admin,  the site didn't redirect and go through the auth process with GitLab e.i. switching the local host for the redirected url.  

BTW. I saw your recent change Assign tokens to user on refresh (https://github.com/plentico/plenti/commit/b7fcda7a2dc60307747bf803ab9bb6dd4bda9e28) and I have upgraded to latest version v0.5.23. 

Pls have a look when you can.
Regards,
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal, this looks like this might be an issue with baseurls. Do you have a `"baseurl": "/my-plenti-site/"` declaration in your `plenti.json` file? If you share a link to your repo I'd be happy to take a look. Thanks!

**Comment by jamestagal** [comment]
Hi @jimafisk 
Yes there is a ```"baseurl": "/my-plenti-site/"```.  This site is the one I added you as a project member so you should have access to it.  https://gitlab.com/MyPlentiSite/my-plenti-site
Thanks
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal, I'm not exactly sure what happened there, the code looked ok so I just [reran your last build](https://gitlab.com/MyPlentiSite/my-plenti-site/-/pipelines/712369934) and that seemed to clear things up. Does it look ok on your end now?

**Comment by jamestagal** [comment]
Hi @jimafisk 
Yes all good now. Thanks 😊
