### ISSUE TITLE
await tick() doesn't work

### ISSUE THREAD

**Issue by Fankhauser-Dominik** [plentico/plenti#259]
It seems, that [tick()](https://svelte.dev/tutorial/tick) doesn't work anymore.
I used the Code from this Gallery (https://github.com/BerkinAKKAYA/svelte-image-gallery/blob/master/Gallery.svelte).
It worked fine, till I updated something on my site.
It seems to me, that the code runs fine till it should use `await tick()`.

Does someone have the same problem?

**Comment by jimafisk** [comment]
That's interesting, was it working previously but now it's broken? Is there a repo or snippet you can share so I can take a look?

@hlanderdev were you able to get `tick()` on a project? Or did you have trouble with it as well?

**Comment by hlanderdev** [comment]
`tick` works for me. The only thing that looks like it would be an issue in that code is the [template string](https://github.com/BerkinAKKAYA/svelte-image-gallery/blob/92ffa25d0161aa93ea7d7349ce74f84ea08981b4/Gallery.svelte#L19). They currently do not work in Plenti.

**Comment by Fankhauser-Dominik** [comment]
I just found out, that my whole Project has now a Problem.
Before the 0.6.0 release, everything worked fine.
I created a new project and copied over my Gallery.svelte, and it immediately worked there.
I also found out, that my Project isn't able to `console.log()` something. With the newly created one, everything works fine.
I guess, the easiest solution is, that I create a new Site and copy everything over.
So tick() wasn't the problem. The entire project ran into a Problem...

**Comment by jimafisk** [comment]
Sorry @Fankhauser-Dominik, the `v0.6.0` release makes a few API adjustments so it will break existing sites. For the most the fixes should be quick:
- Rename `content/index.json` => `content/_index.json`
- Rename `layouts/content/index.svelte` => `layouts/content/_index.svelte`
- If you have a route override for the index content type in `plenti.json` change the key from `index` to `_index`
- Change entrypoint in `layouts/global/head.svelte` from `<script type="module" src="/spa/ejected/main.js"></script>` to `<script type="module" src="/spa/core/main.js"></script>`
- Change your `assets/` folder to `media/`
- Change all JSON content references to use the media folder (e.g. `/assets/my.jpg` => `/media/my.jpg`)
- _Optional:_ Add a `static` folder for things like `global.css`, your site logo, favicon, and other theme files that you don't want content editors changing. Make sure to update the references in your `<head>`.

If you're able to share your repo with me, I can try to help you out with these updates.
