### ISSUE TITLE
Return nested fields as result in autocomplete widget

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#260]
Following up on a conversation with @jamestagal: https://github.com/jamestagal/plenti-educenter/issues/13#issuecomment-1379712941

Currently the autocomplete CMS widget only exposes the top-level metadata for the content:

- pager
- type
- path
- filepath
- filename
- fields (as a full object)

But it would be nice if you could dig into a particular field with dot notation like:

```json
{
  "trainer.name": {
    "type": "autocomplete",
    "options": [
      {
        "type": "teachers",
        "search": [
          "title"
        ],
        "result": "fields.title"
      }
    ]
  }
}
```

**Comment by jamestagal** [comment]
Hi @jimafisk 
Thanks for this update. I completely agree with a name change to ```reference``` here because it functions to ```refer``` to an entity such as a content type so it makes more sense to chose a word that describes the action in the form of a noun. 😀

**Comment by jimafisk** [comment]
Thanks for the feedback @jamestagal! I pushed a change to your educenter theme and it's using the default multivalue field, so I had to pull the value out like `trainer.name[0]`: https://github.com/jamestagal/plenti-educenter/commit/f7fa01bfed88ed066c3c272e9c37f0123f64838a#diff-a478c00b277ced7b3bfacc837eb062e4e001dbe95559f52bf13121a5e76836d0R29

In that case we're only displaying a single item so the single value field (which doesn't exist yet) would be a better choice.

<details>
<summary>See video</summary>

![reference](https://user-images.githubusercontent.com/5913244/212788237-932ac536-63ba-409e-b043-d8ab00709c51.gif)

</details>
