### ISSUE TITLE
New starter style

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#27]
The original vision for the base starter was to look "unfinished" so it's a blank slate for the user to start creating from. Minimalist style can look nice if done right (nice fonts and whitespace). Here was an early attempt at this:

<details>
<summary>Grayscale starter</summary>

![gray](https://user-images.githubusercontent.com/5913244/82109592-3949f400-9705-11ea-8644-4c8e1b4fdffe.png)

</details> 

In the recent pushes, we've moved away from this vision a little bit by introducing a color palette based on the Plenti logo:

<details>
<summary>Color starter</summary>

![color](https://user-images.githubusercontent.com/5913244/82109620-63031b00-9705-11ea-87b9-6796f9fc0811.png)

</details>

Would love input on whether this is headed in the right direction in creating a welcoming introduction to the project, or if we're overdoing it.

**Comment by bketelsen** [comment]
the new colorful minimalist template is just right to my eyes.  It's clear that one would need to do some work to make a personalized site, but it's also clear that there can be styles applied easily.  The purpose of having *some* styles is to show newcomers where to style things and how.

**Comment by jimafisk** [comment]
Thanks for the thoughtful response @bketelsen! I tend to agree with you, giving new users a starting point by default is helpful for exploration. Especially if you pair this with two features we have in the pipeline:
1. Using a `--bare` flag to start with a completely blank slate: https://github.com/plentico/plenti/issues/18
2. Custom starters / themes: https://github.com/plentico/plenti/issues/19
