### ISSUE TITLE
Install in Ubuntu

### ISSUE THREAD

**Issue by gitressa** [plentico/plenti#283]
Looks cool! Just leaving a note that installation only required these steps:

```
cd .local/bin/
wget https://github.com/plentico/plenti/releases/download/v0.6.13/plenti_0.6.13_Linux_64-bit.tar.gz
tar -xvzf plenti_0.6.13_Linux_64-bit.tar.gz 
rm plenti_0.6.13_Linux_64-bit.tar.gz
```

**Comment by jimafisk** [comment]
Yup that'll work @gitressa! You should only need the binary to get up and running, the only thing the package managers do is just download that :). Let me know if you have any questions as you start to play around!
