### ISSUE TITLE
Can't use "plenti" command

### ISSUE THREAD

**Issue by easybeau** [plentico/plenti#296]
Hello,

I installed Plenti on linux (debian) with command : "snap install plenti". 
I can check in a terminal that it's well installed : snap "plenti" is already installed.

But I can’t use the command "plenti new site mysite". I got the error message -> bash: plenti : command unfound.

Thanks for your help and answer,
Best wishes.

**Comment by jimafisk** [comment]
It sounds like this might be a path issue similar to [this issue](https://forum.snapcraft.io/t/bash-hello-world-command-not-found/21391).

If you open a terminal and run `/snap/bin/plenti` does it show any help text for the project or does it still say it's not found?

If you `echo $PATH` in your terminal do you see `/snap/bin` listed there? If not, you should be able to edit your `~/.bashrc` file and add it:
- type `vim ~/.bashrc` in your terminal and press enter to edit the file
- <kbd>Shift</kbd>-<kbd>G</kbd> (jump to bottom of file)
- press <kbd>i</kbd> to enter insert mode
- type `export PATH=$PATH:/snap/bin`
- press <kbd>esc</kbd> to get out of insert mode
- type `:wq` to write and quit the file
- type `source ~/.bashrc` in your terminal to apply the changes

Does that help at all?

**Comment by easybeau** [comment]
Hello,

Thank you so much for your answer. 
Yes it helped. 

It works now !

Best wishes
