### ISSUE TITLE
`plenti serve` on fresh site creation doesnt build

### ISSUE THREAD

**Issue by garlandcrow** [plentico/plenti#32]
Wanted to test this out so did created a new site (both when installed via brew, or installed manually didn't make a difference). 

`plenti new site my-site`
`plenti serve`

Generates this error:

```
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/username/Code/my-site/ejected/build.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
Total build took 152.0681ms

Serving site from your "public" directory.
Visit your site at http://localhost:3000/
```

**Comment by jimafisk** [comment]
Thanks for checking out the project! It looks like you might be using an older version of nodejs? Plenti needs version 13 or newer to support ESM.

I made a video about installing multiple versions with NVM in case it's helpful: https://youtu.be/85D5lAvWRuE

**Comment by garlandcrow** [comment]
Thanks for the quick response. Sorry, totally missed the v13 requirement, that did it.

**Comment by jimafisk** [comment]
Ok nice, I'm glad it worked for you!
