### ISSUE TITLE
SIGSEGV: segmentation violation on running plenti serve on Linux (0.6.45)

### ISSUE THREAD

**Issue by lengani** [plentico/plenti#323]
Excited to try out Plenti (0.6.45) on Manjaro Linux. I am getting the following error on starting plenti: 

plenti serve

Error:

plenti serve                                                                                                    ✔ 

SIGSEGV: segmentation violation
PC=0x29b60 m=0 sigcode=1
signal arrived during cgo execution

goroutine 20 [syscall]:
runtime.cgocall(0xa58f20, 0xc000060588)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc000060560 sp=0xc000060528 pc=0x41652b
net._C2func_getaddrinfo(0xc00022a8c0, 0x0, 0xc000252210, 0xc000114740)
        _cgo_gotypes.go:100 +0x55 fp=0xc000060588 sp=0xc000060560 pc=0x62d455
net._C_getaddrinfo.func1(0x41f7c5?, 0x8?, 0x1ae47e0?, 0x1?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix_cgo.go:78 +0x7a fp=0xc0000605f0 sp=0xc000060588 pc=0x62ddda
net._C_getaddrinfo(0xc00022a7f0?, 0x9?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix_cgo.go:78 +0x13 fp=0xc000060620 sp=0xc0000605f0 pc=0x62dd13
net.cgoLookupHostIP({0x1be5aeb, 0x3}, {0xc00022a7f0, 0x9})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix.go:166 +0x24f fp=0xc000060760 sp=0xc000060620 pc=0x5fd6af
net.cgoLookupIP.func1()
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix.go:215 +0x25 fp=0xc000060790 sp=0xc000060760 pc=0x5fddc5
net.doBlockingWithCtx[...].func1()
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix.go:56 +0x35 fp=0xc0000607e0 sp=0xc000060790 pc=0x62e1b5
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x47ac41
created by net.doBlockingWithCtx[...] in goroutine 19
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix.go:54 +0xd8

goroutine 1 [select]:
runtime.gopark(0xc000195328?, 0x2?, 0xb8?, 0x5?, 0xc000195284?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:398 +0xce fp=0xc0001950d0 sp=0xc0001950b0 pc=0x44b26e
runtime.selectgo(0xc000195328, 0xc000195280, 0xd?, 0x0, 0x0?, 0x1)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/select.go:327 +0x725 fp=0xc0001951f0 sp=0xc0001950d0 pc=0x45ada5
net.(*Resolver).lookupIPAddr(0x39b5160, {0x28e2508?, 0x3a15d00}, {0x1be5aeb, 0x3}, {0xc00022a7f0, 0x9})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/lookup.go:332 +0x3fe fp=0xc0001953d0 sp=0xc0001951f0 pc=0x619f3e
net.(*Resolver).internetAddrList(0x28e2508?, {0x28e2508?, 0x3a15d00?}, {0x1be5aeb, 0x3}, {0xc00022a7f0?, 0x1bbf300?})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/ipsock.go:288 +0x4e5 fp=0xc0001954f8 sp=0xc0001953d0 pc=0x617785
net.(*Resolver).resolveAddrList(0x3a15d00?, {0x28e2508, 0x3a15d00}, {0x1be610a, 0x4}, {0x1be5aeb?, 0x40?}, {0xc00022a7f0, 0xe}, {0x0, ...})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/dial.go:282 +0x405 fp=0xc0001955f8 sp=0xc0001954f8 pc=0x601685
net.(*Dialer).DialContext(0xc000195768, {0x28e2508, 0x3a15d00}, {0x1be5aeb, 0x3}, {0xc00022a7f0, 0xe})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/dial.go:488 +0x42c fp=0xc000195730 sp=0xc0001955f8 pc=0x6025cc
net.(*Dialer).Dial(...)
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/dial.go:433
net.Dial({0x1be5aeb?, 0xc?}, {0xc00022a7f0?, 0x1?})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/dial.go:400 +0x77 fp=0xc0001957e8 sp=0xc000195730 pc=0x6020d7
github.com/plentico/plenti/cmd.checkPortAvailability(0xc000188fc0?)
        /home/runner/work/plenti/plenti/cmd/serve.go:45 +0x74 fp=0xc000195858 sp=0xc0001957e8 pc=0xa526f4
github.com/plentico/plenti/cmd.glob..func8(0xc000160b00?, {0x3a15d00, 0x0, 0x0})
        /home/runner/work/plenti/plenti/cmd/serve.go:94 +0x156 fp=0xc000195d48 sp=0xc000195858 pc=0xa52956
github.com/spf13/cobra.(*Command).execute(0x3951580, {0x3a15d00, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x67b fp=0xc000195e30 sp=0xc000195d48 pc=0x873c9b
github.com/spf13/cobra.(*Command).ExecuteC(0x3951300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x389 fp=0xc000195ee8 sp=0xc000195e30 pc=0x874269
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/plentico/plenti/cmd.Execute()
        /home/runner/work/plenti/plenti/cmd/root.go:48 +0x1a fp=0xc000195f30 sp=0xc000195ee8 pc=0xa5245a
main.main()
        /home/runner/work/plenti/plenti/main.go:7 +0xf fp=0xc000195f40 sp=0xc000195f30 pc=0xa58e0f
runtime.main()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:267 +0x2bb fp=0xc000195fe0 sp=0xc000195f40 pc=0x44ae1b
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000195fe8 sp=0xc000195fe0 pc=0x47ac41

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:398 +0xce fp=0xc000064fa8 sp=0xc000064f88 pc=0x44b26e
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:404
runtime.forcegchelper()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:322 +0xb3 fp=0xc000064fe0 sp=0xc000064fa8 pc=0x44b0f3
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x47ac41
created by runtime.init.6 in goroutine 1
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:398 +0xce fp=0xc000065778 sp=0xc000065758 pc=0x44b26e
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgcsweep.go:280 +0x94 fp=0xc0000657c8 sp=0xc000065778 pc=0x436eb4
runtime.gcenable.func1()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgc.go:200 +0x25 fp=0xc0000657e0 sp=0xc0000657c8 pc=0x42c065
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000657e8 sp=0xc0000657e0 pc=0x47ac41
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0x28d5fa0?, 0x1?, 0x0?, 0xc0000071e0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:398 +0xce fp=0xc000065f70 sp=0xc000065f50 pc=0x44b26e
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x39b5d20)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000065fa0 sp=0xc000065f70 pc=0x434789
runtime.bgscavenge(0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000065fc8 sp=0xc000065fa0 pc=0x434d1c
runtime.gcenable.func2()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgc.go:201 +0x25 fp=0xc000065fe0 sp=0xc000065fc8 pc=0x42c005
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x47ac41
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x198?, 0x1be07a0?, 0x1?, 0xc4?, 0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:398 +0xce fp=0xc000064620 sp=0xc000064600 pc=0x44b26e
runtime.runfinq()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mfinal.go:193 +0x107 fp=0xc0000647e0 sp=0xc000064620 pc=0x42b087
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x47ac41
created by runtime.createfing in goroutine 1
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/mfinal.go:163 +0x3d

goroutine 19 [select]:
runtime.gopark(0xc000153b50?, 0x2?, 0x78?, 0x3b?, 0xc000153b34?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/proc.go:398 +0xce fp=0xc0001539e0 sp=0xc0001539c0 pc=0x44b26e
runtime.selectgo(0xc000153b50, 0xc000153b30, 0x0?, 0x0, 0x4c2700?, 0x1)
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/select.go:327 +0x725 fp=0xc000153b00 sp=0xc0001539e0 pc=0x45ada5
net.doBlockingWithCtx[...]({0x28e2658, 0xc000101360}, 0xc0002521b0)
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix.go:60 +0x14f fp=0xc000153bd0 sp=0xc000153b00 pc=0x62ff6f
net.cgoLookupIP({0x28e2658, 0xc000101360}, {0x1be5aeb, 0x3}, {0xc00022a7f0, 0x9})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/cgo_unix.go:214 +0xb4 fp=0xc000153c00 sp=0xc000153bd0 pc=0x5fdd34
net.(*Resolver).lookupIP(0x39b5160, {0x28e2658, 0xc000101360}, {0x1be5aeb, 0x3}, {0xc00022a7f0, 0x9})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/lookup_unix.go:70 +0x11a fp=0xc000153e58 sp=0xc000153c00 pc=0x61dc3a
net.(*Resolver).lookupIP-fm({0x28e2658?, 0xc000101360?}, {0x1be5aeb?, 0x0?}, {0xc00022a7f0?, 0x0?})
        <autogenerated>:1 +0x49 fp=0xc000153ea0 sp=0xc000153e58 pc=0x6330a9
net.glob..func1({0x28e2658?, 0xc000101360?}, 0x0?, {0x1be5aeb?, 0x0?}, {0xc00022a7f0?, 0x0?})
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/hook.go:23 +0x37 fp=0xc000153ee0 sp=0xc000153ea0 pc=0x610137
net.(*Resolver).lookupIPAddr.func1()
        /opt/hostedtoolcache/go/1.21.9/x64/src/net/lookup.go:324 +0x3a fp=0xc000153f38 sp=0xc000153ee0 pc=0x61a95a
internal/singleflight.(*Group).doCall(0x39b5170, 0xc0001013b0, {0xc00022a800, 0xd}, 0x0?)
        /opt/hostedtoolcache/go/1.21.9/x64/src/internal/singleflight/singleflight.go:93 +0x35 fp=0xc000153fa8 sp=0xc000153f38 pc=0x5fb055
internal/singleflight.(*Group).DoChan.func1()
        /opt/hostedtoolcache/go/1.21.9/x64/src/internal/singleflight/singleflight.go:86 +0x30 fp=0xc000153fe0 sp=0xc000153fa8 pc=0x5faff0
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000153fe8 sp=0xc000153fe0 pc=0x47ac41
created by internal/singleflight.(*Group).DoChan in goroutine 1
        /opt/hostedtoolcache/go/1.21.9/x64/src/internal/singleflight/singleflight.go:86 +0x2e9

rax    0x1
rbx    0x7f88f0671c70
rcx    0x7ffe31d5b7e0
rdx    0x7ffe31d5b7e0
rdi    0x2
rsi    0x7ffe31d5b7c8
rbp    0x2
rsp    0x7ffe31d5a6d8
r8     0x0
r9     0x1a1f6e0
r10    0x7f88f0709990
r11    0x1dd3c0
r12    0x7ffe31d5b7c8
r13    0x7ffe31d5b7e0
r14    0x7f88f0671c80
r15    0x0
rip    0x29b60
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0

--
Please do let me know if you need any system information.

Many thanks,

**Comment by jimafisk** [comment]
Thanks for the bug report @lengani, what editor are you using by chance? Some editors run multiple save events which makes the build process start multiple times and the v8 environment we're using to compile the svelte components errors like this (https://github.com/rogchap/v8go/issues/347). We should make an improvement to pass context and cancel any running builds when a new build request comes in to prevent this from happening (https://github.com/plentico/plenti/issues/109#issuecomment-1575108403).

We've run into similar errors in the past (https://github.com/plentico/plenti/issues/290, https://github.com/plentico/plenti/issues/210, https://github.com/plentico/plenti/issues/45)

**Comment by jimafisk** [comment]
@Crims-on is this happening every time you use the `serve` command, or does it work at first and sometimes when making edits this happens?

**Comment by jimafisk** [comment]
Which operating system (Mac, Linux) do you use @Crims-on? Thanks!

**Comment by tjaynl** [comment]
Same issue here, running Pop OS

**Comment by jimafisk** [comment]
@tjaynl @Crims-on - Thank you both for providing these details! I typically use my local development version so that might be why I never noticed on my machine! A couple of quick questions:
1. Was it just the `serve` command that was broken, but the `build` command was still working? I use the [releases on dockerhub](https://hub.docker.com/r/plentico/plenti) often in CI and it seems to always work. 
2. Were you downloading the binary manually from the [releases tab](https://github.com/plentico/plenti/releases) or were you using snapcraft or some other means to install?
3. When building from source, I assume you're git cloning the project and running `go build`?

> Solved by building from source but then when i do a "plenti version" is gives me undefined as response.

Ah yes that makes sense, the version gets baked in during CI when creating a release: https://github.com/plentico/plenti/blob/4e79177fb0d5cae0cdd32edd1dedd047eaff9fb0/.goreleaser.yml#L11

I'm going to do some testing to try and get this fixed. Thank you!

**Comment by jimafisk** [comment]
This should be fixed in [v0.7.14](https://github.com/plentico/plenti/releases/tag/v0.7.14), so now you should be able to download the binary from the releases page instead of having to build from scratch. If you still run into any issues, please just let me know!

**The problem**
I believe the binary was getting compiled with an older version of glibc (https://github.com/golang/go/issues/60132#issuecomment-2333029657) because we were still using Ubuntu 20.04 in CI. We hadn't upgraded this OS because of compatibility issues with [osxcross-target](https://github.com/plentico/osxcross-target) which provides cgo binaries for Mac.

**The fix**
I updated the [osxcross-target](https://github.com/plentico/osxcross-target) to a newer version to be compatible with Ubuntu 24.04, then updated the OS version used in CI and fixed a few broken build issues (https://github.com/plentico/plenti/issues/347, https://github.com/plentico/plenti/issues/348, https://github.com/plentico/plenti/issues/349).

<hr>

Thank you all for raising this, providing workarounds, and helping debug :heart:
