### ISSUE TITLE
Add flag to "new type" command for single file types

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#36]
The `plenti new type MY_TYPE` command will create a folder at `content/MY_TYPE`. Since plenti allows for single file Types (like `content/index.json` and `content/404.json`) we should add a flag to this command to create a single type file instead of a content type folder. Something like `--single` should work: `plenti new type whatever --single`

**Comment by khang859** [comment]
Hey, love what you're doing with this project, and I would love to contribute where I can with my limited Go knowledge.

I'm a bit confused about the vision for this flag, is it suppose to just create a JSON file?

Thank you!

**Comment by jimafisk** [comment]
Hi @khang859, you're exactly right. The `plenti new type whatever` command normally creates a new content source folder (`content/whatever/`) and a new layout (`layout/content/whatever.svelte`). Then you can put as many .json files as you want in `content/whatever/` and it will create an individual page for each one. Sometimes you have a unique page that will only ever occur once, like the homepage (`content/index.json`) or a "not found" page (`content/404.json`). These are just called "single types" since there will only ever be one of them. A single type does not need a subfolder in `content/`, it can just be put right at the top level (`content/whatever.json`). Does that make sense?

So for this issue, you would roughly take the following steps:

1. Add a new flag here: https://github.com/plentico/plenti/blob/bf6a7653289c5d7405d27756d806c55ec1f07508/cmd/type.go#L94
2. Then somewhere before the folder and the `_blueprint.json` file are create, check for the flag and create a single .json file with the type name instead: https://github.com/plentico/plenti/blob/bf6a7653289c5d7405d27756d806c55ec1f07508/cmd/type.go#L49

Just let me know if you have any questions! Thanks for taking a look!

**Comment by khang859** [comment]
@jimafisk I took a stab at it, let me know if anything need to be changed! https://github.com/plentico/plenti/pull/83

**Comment by jimafisk** [comment]
Thanks so much @khang859! I'll take a look!

**Comment by jimafisk** [comment]
Thanks again for the help on this @khang859, your work was included in the new [v0.3.0 release](https://github.com/plentico/plenti/releases/tag/v0.3.0)! We'd love to give you a shout out for your contribution, are you on twitter?

**Comment by khang859** [comment]
@jimafisk No problem! I am not on twitter, thank you though.
