### ISSUE TITLE
scoop install fails

### ISSUE THREAD

**Issue by mjosborne1** [plentico/plenti#44]
I tried to use scoop to install plenti, but it fails as per below:

PS C:\code\www\examples> scoop bucket add org https://github.com/plentico/scoop-plenti.git
WARN  The 'org' bucket already exists. Use 'scoop bucket rm org' to remove it.
PS C:\code\www\examples> scoop install plentico/scoop-plenti
WARN  Bucket 'plentico' not installed. Add it with 'scoop bucket add plentico' or 'scoop bucket add plentico <repo>'.
**Couldn't find manifest for 'scoop-plenti' from 'plentico' bucket.**

**Comment by jimafisk** [comment]
Thanks for trying this out @mjosborne1, I actually hadn't checked installing on Windows yet. I'll give this a whirl to see if I can figure out what's going wrong.

**Comment by mjosborne1** [comment]
I also tried the snap install on Windows Linux subsystem...

michael@DESKTOP-EQM3S51:~/docker$ snap install plenti
Interacting with snapd is not yet supported on Windows Subsystem for Linux.
This command has been left available for documentation purposes only.
So I guess with brew unavailable on my Dell XPS, I have no other options.

**Comment by jimafisk** [comment]
Snap actually has some other issues at the moment (https://github.com/plentico/plenti/issues/31) that should be resolve on the 0.2.0 version that I'm hoping to push out soon.

One thing you can try is manually installing the binary on Windows. Just grab the latest [64 bit release](https://github.com/plentico/plenti/releases/download/v0.1.26/plenti_0.1.26_Windows_64-bit.tar.gz) ([32 bit](https://github.com/plentico/plenti/releases/download/v0.1.26/plenti_0.1.26_Windows_32-bit.tar.gz) is also available). That should contain a `plenti.exe` file you can run, but you might need a program like [7-zip](https://www.7-zip.org/) to uncompress the download to get access to the executable file (see instructions here: https://superuser.com/questions/215629/how-to-open-a-tar-gz-file-in-windows). Or if you want to use the Command Prompt to extract the files:
1. `cd C:\Users\YOURUSER\Downloads`
2. `tar -C . -xvf plenti_0.1.26_Windows_64-bit.tar.gz`

Then go back to your Downloads folder and just double click on the file called "plenti" to install it. After that if you should be able to type "plenti" into the command prompt and it should work.

<details>
<summary>Screenshot from the Windows test I just did</summary>

![plenti_windows](https://user-images.githubusercontent.com/5913244/87840036-9bd98080-c86b-11ea-9612-52743419acb4.png)

</details>

Just let me know if that doesn't work for you!

**Comment by mjosborne1** [comment]
Thanks - I got plenti installed OK, just there seems to be an issue running the build/serve command on Windows...Looks like a go server error. Please see my other Issue https://github.com/plentico/plenti/issues/45

**Comment by jimafisk** [comment]
Just downloaded [scoop](https://scoop.sh/) for testing:
1. Open up PowerShell on Windows 10
2. `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`
3. Type `y` for yes and press enter
4. `iwr -useb get.scoop.sh | iex`

<details>
<summary>Screenshot</summary>

![scoop](https://user-images.githubusercontent.com/5913244/87840670-e0b2e680-c86e-11ea-9335-01ed72b7caf6.png)

</details>

I had the instructions wrong for installing with scoop. The following should work:
1. `scoop install git`
2. `scoop bucket add plenti https://github.com/plentico/scoop-plenti`
3. `scoop install plenti`

<details>
<summary>Screenshot</summary>

![scoopplenti](https://user-images.githubusercontent.com/5913244/87841335-a2b7c180-c872-11ea-8e53-7db82d8af1a0.png)

</details>

@mjosborne1 do those updated instructions ^ work for you?

**Comment by jimafisk** [comment]
Updated the README: https://github.com/plentico/plenti/commit/9f00bf3f9092ddc8fcfadf017ecb6092ebf76f7d
