### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#46]
I'm unsure about how intuitive some of the default folder names are. My intent was that this would be mostly decoupled from the generator so users could name them whatever they want, and although that's somewhat true, some of this namespace is required for plenti to function.

The goal is not necessarily to keep with tradition of any particular methodology (e.g. in JS it's common to see `src/` and `dist/` folders), but instead aim for what is most intuitive and least intimidating to new users, especially those with limited technical experience. Ideally the dev experience will be easy for everyone, but if tradeoffs have to be made, I'd emphasize adaptation happening with experienced devs over inexperienced devs who are learning many concepts simultaneously.

Proposed change 1:
Rename `assets/` => `files/`
I originally used "assets" because it seemed more all encompassing of static material that might go into this folder and fit with convention of some other projects. This term might be obscure for folks who have never heard of terms like "asset pipeline" and might not intuitively know what this folder should be used for. The term "files" on the other hand is a laymen term for things like photos, videos, etc. I originally didn't like this term because technically everything in plenti is a file, but I think the way it is commonly used would be easily understood by more people without having to look to documentation.

Proposed change 2:
Rename `layout/content/` => `layout/routes/`
I originally used "content" because I wanted it to match the folder name of the data source that feeds it (there should be a 1-to-1 relationship between types and route layouts). Although it probably does help make that connection, it also obfuscates the fact that this folder is directly related to endpoints that visitors can navigate to. A downside of changing this to "route" is that each file in this folder can serve many routes so they are really just layouts for individual content files that determine the route.

**Comment by mjosborne1** [comment]
RE: Proposed change 1, I think the term 'files' is ambiguous a file can be anything, especially in a linux/unix system. Most people are used to puting static things js/img/css is assests or a folder called 'static'. I like `static` as a name, it a functional name, you can say everything in static is copied over to dist/public 'as is' and accessed from the root url path. 

I support proposed change 2 for the same reasons as my comments above, it desccirbes the function of the directory. You just need some doco somewhere that talks about routes that are folders, versus a single file.

**Comment by jimafisk** [comment]
Thanks for the feedback @mjosborne1! I was considering `static` as well. My concern was that since plenti is a static site generator, I was worried folks might confuse this as the folder for the static output, which we're calling `public` by default. Your point about `files` is well taken, maybe `assets` is our best option for the time being?

I definitely should put some clarifying docs together regarding routing. I appreciate the input!

**Comment by jimafisk** [comment]
Something that I'd like to change is the `nodes.js` file that plenti uses internally to aggregate all the content. I initially used the term `node` because each piece of content in this folder was a unique endpoint (route) that you could visit in the browser. We now allow optional endpoints (https://github.com/plentico/plenti/issues/13) so calling these "nodes" no longer makes sense. I also don't like that the name `nodes.js` sounds similar to `NodeJS` even though the two things are unrelated.

**Proposal:** Rename `node` references to `content`. This will more closely tie this to its source (the `content/` folder) and avoid confusion outlined above. My guess is the term `content` is more approachable for someone without a technical background, but that's speculation. 

**Action Plan:**
- Change the `nodes.js` file created by `data_source.go` to `content.js`
- Update variable names in Go:
    - `nodeDetailsStr`
    - `nodesJsFile`
    - `encodedNodeDetails`
    - `allNodesStr`
- Change the `node` prop to `content`
- Change the `allNodes` prop to `allContent`

**Comment by jimafisk** [comment]
Folder structure ideas from [Svelte Master](https://www.youtube.com/channel/UCg6SQd5jnWo5Y70rZD9SQFA):

> Have a "content" folder and a "routes" folder where the content corresponds to the routes folder (kinda like you already have) - and then have your layout/content/html.svelte file as like routes/_html.svelte since it's "special"
