### ISSUE TITLE
How to handle "complex types"?

### ISSUE THREAD

**Issue by kbsali** [plentico/plenti#77]
Hello,

I would like to try and build a site with pages containing an html table made of what I imagine to be sort of a "complex type" : an array of "regular types". How would you handle such a case?
eg:
```json
[
	{
		"key1": "value 1",
		"key2": "value 2",
		"key3": "value 3",
	},
	{
		"key1": "value 10",
		"key2": "value 20",
		"key3": "value 30",
	},
	...
]
```

**Comment by jimafisk** [comment]
Hi @kbsali,

Let's say you want to add a table to your homepage, I might do something like this:

In `content/index.json`:
```json
{
  "title": "My table",    
  "table": {
    "head": ["key1", "key2", "key3"],
    "body" : [  
      {                              
        "key1": "value 1",
        "key2": "value 2",
        "key3": "value 3"   
      },             
      {      
        "key1": "value 4",
        "key2": "value 5", 
        "key3": "value 6"
      }
    ]
  }
}
```

In `layout/content/index.svelte`:
```svelte
<script>
  export let title, table;
</script>   

<h1>{title}</h1>

<table>
  <tr>
    {#each table.head as th}
      <th>{th}</th>  
    {/each}  
  </tr>
  {#each table.body as row}
    <tr>
      {#each Object.entries(row) as [i, td]}
        <td>{td}</td>
      {/each}
    </tr>
  {/each}
</table>
```

**Note** You can't loop through objects the same way you do arrays, thus the `Object.entries()` syntax (see more details here: https://github.com/sveltejs/svelte/issues/894#issuecomment-620142025) 

That should give you something like this:

![table](https://user-images.githubusercontent.com/5913244/97120473-905ce780-16ed-11eb-93c3-a3f1ee754765.png)

That's just one way of doing it. The structure is pretty flexible so you could actually omit the "head" key entirely and just pull the actual keys out of your `td` object for the thead, but I thought being more verbose might highlight what's going on better. Let me know if you're still stuck!

**Comment by kbsali** [comment]
Awesome, thanks for the detailed answer, I'll give it a try!
