### ISSUE TITLE
Themes (Coming Soon)

### ISSUE THREAD

**Issue by lgs** [plentico/plenti#80]
Any roadmap about ["Themes (Coming Soon)"](https://plenti.co/themes)?

**Comment by jimafisk** [comment]
It's not much of a roadmap, but I'm collecting thoughts over at https://github.com/plentico/plenti/issues/37. I have a lot of the high level concepts worked out in my head, so at some point I'll add more details to that ticket about how things are going to work. If you have ideas about how this should work, I would love to hear them still.

I actually just started work on this, so there's an open PR to keep an eye on as well: https://github.com/plentico/plenti/pull/79. I'm hoping to have a rough implementation by early next week, depending on how much client work I have to do this week. 

Once the themes functionality is ready, we'll still need to actually create the themes listed on the website to give folks a starting point. The ones listed on the website are all existing themes from other SSGs so I'll just need to port them over. Creating a theme is the exact same process as creating any ordinary plenti site. If folks want to help with that when the time comes, that would be awesome!

**Comment by jimafisk** [comment]
Themes should be working in general, here's a quick demo on how to get started: https://youtu.be/dT69Ph2XkjQ?t=1904

There's still a lot of work to be done actually building out some themes for folks to play around with, so I'll leave this issue open until we've added a few to the website: https://plenti.co/themes
