### ISSUE TITLE
Multi language sites

### ISSUE THREAD

**Issue by leaanthony** [plentico/plenti#84]
Great project!

What's the best approach for multi language sites?

Thanks.

**Comment by jimafisk** [comment]
Thanks @leaanthony! Are you hoping to use subdirectories to distinguish between languages (e.g. `mysite.com/en`, `mysite.com/fr`)? The easiest thing to do would be to nest language folders within your content types. I just created an example project to illustrate what this might look like: https://github.com/jimafisk/plenti-multilingual-example

I think one area we could improve upon is allowing the nested folder structure to be a replacement pattern for the route in `plenti.json`. In the example project above you'll notice the urls all start with `pages/`. If you wanted to remove this we currently give a `:filename` replacement pattern (see https://github.com/plentico/plenti/issues/14) but that won't give you the nested "en" or "fr" value. We should add another route replacement pattern like `:path` or `:nested` to get this information. This would also be helpful for people who like to organize things like blogs into date folders (e.g. `content/blog-posts/2020/10/19/post.json` but want to change the content type name so the route looks different `/blog/2020/10/19/post`). A way you could get around this in the meantime is just to add that information to your content source as a field and then use it as a route replacement value. Basically every content file would look like:

```json
{
  "title": "Your page title",
  "lang": "en"
}
```
Then in `plenti.json`:
```json
"types": {             
  "pages": "/:field(lang)/:filename"
},
```
^ it's just a little annoying to have to add the "lang" key to every file even though it's already in the `content/pages/en/` folder.

**Comment by leaanthony** [comment]
I appreciate you taking the time to make an example project! I'll experiment with it and provide feedback.
