### ISSUE TITLE
Add to chocolatey.org

### ISSUE THREAD

**Issue by frederikhors** [plentico/plenti#88]
You should add https://chocolatey.org/ for Windows installation.

**Comment by jimafisk** [comment]
Thanks for flagging this @frederikhors! I had added [scoop](https://scoop.sh/) support but I haven't developed on Windows in a while, do most folks prefer Chocolatey?

It would be great if there were goreleaser support for this: https://github.com/goreleaser/goreleaser/issues/131

The big issue at the moment however, is **Windows support for Plenti is broken** (see https://github.com/plentico/plenti/issues/45). It's something I need to address and would love help on if anyone is familiar with Go and Windows. Thanks!

**Comment by jimafisk** [comment]
The top comment on [this post](https://dev.to/bowmanjd/chocolatey-vs-scoop-package-managers-for-windows-2kik) makes it sound like scoop might be preferable for most windows devs: 
> Scoop let's you define package repositories (buckets) in a simple JSON format, whereas Chocolatey requires a NuGet v2 feed. Chocolatey imposes a hard request limit to their public repositories, so you can't use it for production without hosting your own repository. If you read this comment and you are looking for a tool to provision software to Windows-machines in a Linux-style manner, save yourself some time and choose scoop.

We have [problems](https://github.com/plentico/plenti/issues/45) running windows on plenti in general that we need to fix before we can get to this. I'm going to close this for now until we get those resolved and there is a path forward for adding Chocolatey support to Goreleaser: https://github.com/goreleaser/goreleaser/issues/131
