### ISSUE TITLE
How update extend Plenty project?

### ISSUE THREAD

**Issue by Valexr** [plentico/plenti#95]
How update extend Plenty project?

**Comment by jimafisk** [comment]
Hi @Valexr, are you looking to update the [NPM](https://www.npmjs.com/) packages that ship with Plenti, upgrade Plenti itself to a newer version, or is there something else you're hoping to accomplish?

**Comment by jimafisk** [comment]
Hi @Valexr, if you still need more help here, please let me know. If you're hoping to update Plenti itself, you should be able to use your package manager's normal update process (e.g. on Mac it would be `brew upgrade plenti`).

I'm going to close this issue for now, but If that gives you any trouble or I'm not understanding your question, just let me know! Thanks!
