### ISSUE TITLE
Unable to read content type source file: invalid character 'b' looking for beginning of value 

### ISSUE THREAD

**Issue by aphsa** [plentico/plenti#96]
After trying to modify the title value in index.json:

plentisite$ cat content/index.json
```json
{
        "title": "Plenti Site"
}
```
Total build took 310.628988ms
Unable to read content type source file: invalid character 'b' looking for beginning of value
Could not create props: SyntaxError: Unexpected number
Can't render htmlComponent: ReferenceError: props is not defined
Could not create props: SyntaxError: Unexpected number
Can't render htmlComponent: ReferenceError: props is not defined
Total build took 300.713962ms

**Comment by jimafisk** [comment]
So you only changed the title from "My Plenti Site" to "Plenti Site" and it blew up? The error `Unable to read content type source file` makes it sound like there might be some invalid JSON somewhere, are you able to share a link to the repo? Thanks!

**Comment by aphsa** [comment]
The issue stopped after I restarted  the plenti service.

**Comment by jimafisk** [comment]
Ok nice! Maybe something happened with [fsnotify](https://github.com/fsnotify/fsnotify) when it was trying to watch for file updates. Just let me know if it gives you any more trouble!
